us_states = ['WA', 'Washington', 'WI', 'Wisconsin',
    'WV', 'West Virginia', 'FL',
    'Florida', 'WY', 'Wyoming', 'NH',
    'New Hampshire', 'NJ', 'New Jersey',
    'NM', 'New Mexico', 'NA',
    'National', 'NC', 'North Carolina',
    'ND', 'North Dakota', 'NE',
    'Nebraska', 'NY', 'New York', 'RI',
    'Rhode Island', 'NV', 'Nevada',
    'GU', 'Guam', 'CO', 'Colorado',
    'CA', 'California', 'GA', 'Georgia',
    'CT', 'Connecticut', 'OK',
    'Oklahoma', 'OH', 'Ohio', 'KS',
    'Kansas', 'SC', 'South Carolina',
    'KY', 'Kentucky', 'OR', 'Oregon',
    'SD', 'South Dakota', 'DE',
    'Delaware', 'DC',
    'District of Columbia', 'HI',
    'Hawaii', 'PR', 'Puerto Rico', 'TX',
    'Texas', 'LA', 'Louisiana', 'TN',
    'Tennessee', 'PA', 'Pennsylvania',
    'VA', 'Virginia', 'VI',
    'Virgin Islands', 'AK', 'Alaska',
    'AL', 'Alabama', 'AS',
    'American Samoa', 'AR', 'Arkansas',
    'VT', 'Vermont', 'IL', 'Illinois',
    'IN', 'Indiana', 'IA', 'Iowa', 'AZ',
    'Arizona', 'ID', 'Idaho', 'ME',
    'Maine', 'MD', 'Maryland', 'MA',
    'Massachusetts', 'UT', 'Utah', 'MO',
    'Missouri', 'MN', 'Minnesota', 'MI',
    'Michigan', 'MT', 'Montana', 'MP',
    'Northern Mariana Islands', 'MS',
    'Mississippi'
]

print len(us_states)

        
